- name: "Tables"
  remove_surface: true
  require_surface: true
  parent_frame_id: "base_link"
  child_frame_id: "head_camera_link"
  bounding_frame_id: "base_link"
  segmentation_frame_id: "base_link"
  x_max: 1.5
  z_min: 0.2
  pitch_max: 1.07
- name: "Base"
  remove_surface: true
  require_surface: true
  parent_frame_id: "base_link"
  child_frame_id: "head_camera_link"
  bounding_frame_id: "base_link"
  segmentation_frame_id: "base_link"
  z_min: 0.2
  pitch_min: 1.07
  pitch_max: 2.0
